Beta rii accounts
stfc/infrastructure-portal pull request #8
Opened 2021-11-30 17:09 UTC by AJO-Python

Merging rii_accounts.

Adds a custom module for use with the ContentImport contrib module.
When new RII are added via imported CSV, a user account, group, and infrastructure are created and assigned.
Also fixes some database fields that are not parsed correctly by ContentImport

2021-11-30 18:39 UTC, akademy requested changes
This all looks pretty good but there's a few things I'd like looking at. If something doesn't make sense (or maybe you don't agree with) just let me know.

2021-11-30 18:39 UTC, akademy commented on modules/custom/rii_accounts/src/Controller/RiiAccountsController.php
> +            '#markup' => 'Content test: ' . $author_email,
Is this test code?

2021-11-30 18:39 UTC, akademy commented on modules/custom/rii_accounts/rii_accounts.module
> +    $host = "mysql-dev";
These database details need to be removed. But as this is a Drupal module you should be able to access the settings in here. Alternatively you could use the Drupal database connection with
`$connection = \Drupal::database();`

2021-11-30 18:39 UTC, akademy commented on modules/custom/rii_accounts/rii_accounts.module
> +        $node_name = $node->label(); // TODO: Check name is unique in DB
We should add this to the todo list. And let the admins know.

2021-11-30 18:39 UTC, akademy commented on modules/custom/rii_accounts/rii_accounts.module
> +    $user->setPassword("password"); // TODO: Remove when not testing
Can we remove please! 
Also, does the user receive this password in an email at this point?

2021-11-30 18:39 UTC, akademy commented on modules/custom/rii_accounts/rii_accounts.module
> +                ->update("$table")
$table is already a string, you don't have to put it in another string. (repeated a few lines down too).

2021-11-30 18:39 UTC, akademy commented on modules/custom/rii_accounts/rii_accounts.module
> +        $connection
I like things to align, can you correct the indentation here please.

2021-11-30 18:39 UTC, akademy commented on modules/custom/rii_accounts/rii_accounts.module
> +        // It is pre-populated with the full string containg all keywords
```suggestion
        // It is pre-populated with the full string containing all keywords
```

2021-11-30 18:39 UTC, akademy commented on modules/custom/rii_accounts/rii_accounts.module
> +function var_dump_ret($mixed = null) {
Don't think this is used so can be removed.

2021-11-30 18:39 UTC, akademy commented on modules/custom/rii_accounts/rii_accounts.module
> +function connect_pdo() {
This is a bit of a pain but can you rename the functions to first begin with "rii_accounts_".

This is due to PHP being crap at separating code in different files. It's better to use a more unique name so that clashes don't occur with functions in other files.

2021-11-30 18:47 UTC, akademy commented on modules/custom/rii_accounts/rii_accounts.module
> +?>
And could you remove these php closing tags from the end of the file please. They aren't necessary and in some situations can cause problems (if something is present after them they can cause PHP to send invalid data)

2021-12-01 11:32 UTC, AJO-Python commented on composer.json
> +        "wikimedia/composer-merge-plugin": "^2",
Maybe not strictly in the ContentImport changes... but I will make a branch for this change.

Its the module that causes issues with Composer as it requires Composer v1 to be able to interact with it at all. Then the deletions on lines 97 and 121-122 are also required to get the module working with composer v2

2021-12-01 11:35 UTC, AJO-Python commented on modules/contrib/contentimport/contentimport.module
> +                break;
This is the address changes I've had to add to the actual ContentImport module rather than rii_accounts - without this the data is lost in the initial import and rii_accounts has nothing to work with.

Is there anything to be aware of if we commit this change to a contrib module? i.e it may be overwritten with a composer update and it needs to be added as a patch instead?

2021-12-01 11:41 UTC, AJO-Python commented on dev-notes.md
> +Developer Notes
I'm not sure either - the only new bit should be lines 3-4 about Drush in Docker containers

2021-12-01 11:41 UTC, AJO-Python commented on dev-notes.md
> +Developer Notes
Should I just remove the file from the PR and I can add those changes directly to beta-dev?

2021-12-07 16:15 UTC, AJO-Python commented on modules/custom/rii_accounts/src/Controller/RiiAccountsController.php
> +            '#markup' => 'Content test: ' . $author_email,
yes - I will remove this

2021-12-07 16:19 UTC, AJO-Python commented on modules/custom/rii_accounts/rii_accounts.module
> +function var_dump_ret($mixed = null) {
yep this is a printing function to help debug. Completely slipped my mind to remove it

2021-12-15 14:01 UTC, AJO-Python commented on modules/custom/rii_accounts/rii_accounts.module
> +        $node_name = $node->label(); // TODO: Check name is unique in DB
Should I leave it as a TODO item in the code for now? Or remove that comment and bring it up with Joe and Steph?

2022-03-18 16:02 UTC, closed without merging